version: '3.7'
services:
  nginx:
    image: nginx:1.19.1-alpine
    restart: on-failure
    volumes:
      - ./public/:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - 80
    networks:
      - default
      - nginx-proxy
    environment:
      VIRTUAL_HOST: vi-test.loc
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: on-failure
    volumes:
      - ./:/usr/src/app${VOLUMES_FLAG}

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker/mysql/data:/data/db

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
